[package]
name = "pallograph"
version = "0.1.0"
edition = "2024"

[build-dependencies]
mangle-ast    = { git = "https://codeberg.org/ajwdev/mangle-rs.git", branch = "ajw-backport-old-funcs" }
mangle-driver = { git = "https://codeberg.org/ajwdev/mangle-rs.git", branch = "ajw-backport-old-funcs" }
glob          = "0.3"

[dependencies]
mangle-ast         = { git = "https://codeberg.org/ajwdev/mangle-rs.git", branch = "ajw-backport-old-funcs" }
mangle-parse       = { git = "https://codeberg.org/ajwdev/mangle-rs.git", branch = "ajw-backport-old-funcs" }
mangle-common      = { git = "https://codeberg.org/ajwdev/mangle-rs.git", branch = "ajw-backport-old-funcs" }
mangle-driver      = { git = "https://codeberg.org/ajwdev/mangle-rs.git", branch = "ajw-backport-old-funcs" }
mangle-interpreter = { git = "https://codeberg.org/ajwdev/mangle-rs.git", branch = "ajw-backport-old-funcs" }
mangle-analysis    = { git = "https://codeberg.org/ajwdev/mangle-rs.git", branch = "ajw-backport-old-funcs" }
mangle-ir          = { git = "https://codeberg.org/ajwdev/mangle-rs.git", branch = "ajw-backport-old-funcs" }

serde       = { version = "1", features = ["derive"] }
serde_json  = { version = "1", features = ["preserve_order"] }
serde_yaml  = "0.9"
toml        = "0.8"
dirs        = "5"
anyhow      = "1"
clap        = { version = "4", features = ["derive"] }
rustyline   = "14"
glob        = "0.3"
kube        = { version = "0.95", features = ["client"] }
k8s-openapi = { version = "0.23", features = ["v1_31"] }
tokio       = { version = "1", features = ["rt-multi-thread", "macros"] }
self_cell = "1.2.2"
differential-dataflow = "0.23.0"
timely = "0.29.0"
z3 = "0.12"

[features]
z3-static = ["z3/static-link-z3"]
